services: 
  mysql-nest-db:
    image: mysql:8
    container_name: mysql-nest-db
    volumes:
      - nest-api-db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nest-api-db
      - MYSQL_USER=admin  
      - MYSQL_PASSWORD=root
    networks:
      - first-network  

  nest-api:
    build: 
      context: .
    container_name: nest-api
    ports:
      - 3001:3000
    depends_on:
      - mysql-nest-db
    networks:
      - first-network

networks:
  first-network:
    driver: bridge

volumes:
  nest-api-db:

