name: CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [20, 22, lts/*, latest]

    steps:
      - uses: actions/checkout@v5.0.1

      # - name: Setup Node.js environment | Node ${{ matrix.node }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0
        with:
          # node-version: ${{ matrix.node }}
          node-version: 22
          cache: 'npm'
      - run: npm i
      - run: npm run test

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ECR_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build and push docker image
        id: build-and-push-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry}}
          TAG: ${{ steps.generate_tag.outputs.sha }}
        run: |
          docker build -t ${{ env.REGISTRY }}/devops-nest-api:${{ env.TAG }} .
          docker push ${{ env.REGISTRY }}/devops-nest-api:${{ env.TAG }}
          docker tag ${{ env.REGISTRY }}/devops-nest-api:${{ env.TAG }} ${{ env.REGISTRY }}/devops-nest-api:latest
          docker push ${{ env.REGISTRY }}/devops-nest-api:latest
          IMAGE=$(echo ${{ env.REGISTRY }}/devops-nest-api:${{ env.TAG }})
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Deploy to AWS App Runner
        id: deploy-to-app-runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: devops-nest-api
          image: ${{ steps.build-and-push-image.outputs.image }}
          access-role-arn: ${{ secrets.AWS_APP_RUNNER_ROLE }}
          region: ${{ vars.AWS_REGION }}
          cpu: 1
          memory: 2
          port: 3000
          wait-for-service-stability-seconds: 180

      - name: App Runner URL
        run: echo "App Runner running... ${{ steps.deploy-to-app-runner.outputs.service-url }}"
