name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [20, 22, lts/*, latest]

    steps:
      - uses: actions/checkout@v5.0.1

      # - name: Setup Node.js environment | Node ${{ matrix.node }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0
        with:
          # node-version: ${{ matrix.node }}
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm run test

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ECR_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1
      # - name: Login into the container registry
      #   uses: docker/login-action@v3.6.0
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and Push image
      #   uses: docker/build-push-action@v6.18.0
      #   with:
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-nest-api:${{ steps.generate_tag.outputs.sha }},${{ secrets.DOCKERHUB_USERNAME }}/devops-nest-api:latest

      # - name: Build docker image
      #   run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-nest-api:${{ steps.generate_tag.outputs.sha }} .

      # - name: Push image to container registry
      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-nest-api:${{ steps.generate_tag.outputs.sha }}
